import time
from dataclasses import dataclass
from pathlib import Path

import paramiko

from configurer.core.models import CertsManager, WazuhComponentConfigManager
from generic import exec_command, exec_command_with_status, remote_connection
from models import Inventory
from utils import CertificatesComponent, Component, Logger, RemoteDirectories

logger = Logger("CoreConfigurer")

# The Wazuh manager automatically generates a random Authd registration password on startup
# and persists it in this file. The Wazuh agent needs that same password to enroll against
# the manager, so it is copied to the agent Authd password file.
WAZUH_MANAGER_AUTHD_PASS_FILE = "/var/wazuh-manager/etc/authd.pass"
WAZUH_AGENT_AUTHD_PASS_FILE = "/var/ossec/etc/authd.pass"
# The manager generates its Authd password on startup, so wait for the file to appear.
AUTHD_PASS_MAX_RETRIES = 12
AUTHD_PASS_WAIT_TIME = 5

# The manager's self-signed remoted certificate (HTTPS agent listener identity, reused by Authd
# as the /enroll mTLS credential) is generated by the wazuh-manager package postinstall, so unlike
# authd.pass it already exists by the time this configurer runs and needs no startup wait. The
# agent is configured to trust it directly, since it's the only certificate the manager's HTTPS
# listener ever presents.
WAZUH_MANAGER_REMOTED_CERT_FILE = "/var/wazuh-manager/etc/certs/remoted.pem"
WAZUH_AGENT_CA_FILE = "/var/ossec/etc/certs/root-ca.pem"

# `wazuh-manager-keystore` stores its values in a RocksDB-backed file (queue/keystore) that a
# just-started manager daemon may still be opening -- `systemctl start` returns as soon as the
# unit is "active", not once every daemon inside it has finished initializing -- so the keystore
# CLI can lose the exclusive-lock race immediately after start. Retry instead of failing outright.
MANAGER_KEYSTORE_MAX_RETRIES = 6
MANAGER_KEYSTORE_WAIT_TIME = 5


@dataclass
class CoreConfigurer:
    inventory: Inventory | None
    files_configuration_path: Path

    @remote_connection
    def configure(self, client: paramiko.SSHClient | None = None):
        """
        Configures the core components and manages certificates.

        This method performs the following steps:
        1. Configures the Wazuh components (Indexer, Manager, Dashboard) by replacing file entries
        using the WazuhComponentConfigManager.
        2. Generates certificates using the CertsManager and copy them to the current component certs directory.
        3. Starts the Wazuh services.

        Args:
            client (paramiko.SSHClient | None): An optional SSH client to use for remote operations. Defaults to None.
        """

        logger.debug_title("Starting core configuration process")

        logger.debug_title("Configuring components")
        config_mappings = WazuhComponentConfigManager(files_configuration_path=self.files_configuration_path)
        config_mappings.replace_file_entries(Component.WAZUH_INDEXER, client=client)
        config_mappings.replace_file_entries(Component.WAZUH_MANAGER, client=client)
        config_mappings.replace_file_entries(Component.WAZUH_DASHBOARD, client=client)
        config_mappings.replace_file_entries(Component.WAZUH_AGENT, client=client)
        logger.info_success("Core configuration process finished")

        logger.debug_title("Starting certificates creation and configuration process")
        certs_manager = CertsManager(
            raw_config_path=Path(RemoteDirectories.CERTS) / CertificatesComponent.CONFIG,
            certs_tool_path=Path(RemoteDirectories.CERTS) / CertificatesComponent.CERTS_TOOL,
            client=client,
        )
        certs_manager.generate_certificates(client=client)

        logger.debug_title("Starting services")
        self.start_services(client=client)

    def start_services(self, client: paramiko.SSHClient | None = None):
        command = "sudo systemctl daemon-reload"
        output, error_output = exec_command(command=command, client=client)
        if error_output:
            logger.error("Error reloading daemon")
            raise RuntimeError(f"Error reloading daemon {error_output}")

        for component in Component:
            if component != Component.ALL:
                logger.debug(f"Starting {component.replace('_', ' ')} service...")

                # The manager (started in a previous iteration) has already generated its Authd
                # password, so copy it to the agent before enrolling it against the manager.
                if component == Component.WAZUH_AGENT:
                    self.set_authd_password(client=client)
                    self.set_agent_ssl_ca(client=client)

                command = f"""
                    sudo systemctl --quiet enable {component.replace("_", "-").lower()}
                    sudo systemctl start {component.replace("_", "-").lower()}
                    """

                if component == Component.WAZUH_INDEXER:
                    command += "sudo /usr/share/wazuh-indexer/bin/indexer-security-init.sh"

                output, error_output = exec_command(command=command, client=client)
                if error_output:
                    logger.error(f"Error starting {component} service")
                    raise RuntimeError(f"Error starting {component} service: {error_output}")

                if component == Component.WAZUH_MANAGER:
                    self.set_manager_keystore(client=client)

                logger.debug(f"{component.replace('_', ' ')} service started")

        logger.info_success("All services started")

    def set_authd_password(self, client: paramiko.SSHClient | None = None):
        """
        Configures the Wazuh agent registration password.

        Reads the Authd password automatically generated and stored by the Wazuh manager in its
        ``authd.pass`` file and writes it, with the proper ownership and permissions, to the Wazuh
        agent ``authd.pass`` file. This lets the agent enroll against the manager and reproduces the
        behavior of the ``WAZUH_REGISTRATION_PASSWORD`` installation parameter for the pre-installed
        agent shipped in the OVA and AMI.

        Args:
            client (paramiko.SSHClient | None, optional): An SSH client to execute the commands
                remotely. If None, the commands are executed locally. Defaults to None.

        Raises:
            RuntimeError: If the manager Authd password file is not found or the agent registration
                password cannot be set.
        """

        logger.debug("Setting the Wazuh agent registration password from the manager Authd password")

        for attempt in range(AUTHD_PASS_MAX_RETRIES):
            output, _ = exec_command(
                command=f"sudo test -f {WAZUH_MANAGER_AUTHD_PASS_FILE} && echo found", client=client
            )
            if "found" in output:
                break
            logger.debug(
                f"Manager Authd password file not ready yet, retrying in {AUTHD_PASS_WAIT_TIME} seconds "
                f"(attempt {attempt + 1}/{AUTHD_PASS_MAX_RETRIES})"
            )
            time.sleep(AUTHD_PASS_WAIT_TIME)
        else:
            logger.error("Wazuh manager Authd password file not found")
            raise RuntimeError(f"Wazuh manager Authd password file not found at {WAZUH_MANAGER_AUTHD_PASS_FILE}")

        command = f"""
            sudo cp {WAZUH_MANAGER_AUTHD_PASS_FILE} {WAZUH_AGENT_AUTHD_PASS_FILE}
            sudo chown root:wazuh {WAZUH_AGENT_AUTHD_PASS_FILE}
            sudo chmod 640 {WAZUH_AGENT_AUTHD_PASS_FILE}
            """
        _, error_output = exec_command(command=command, client=client)
        if error_output:
            logger.error("Error setting the Wazuh agent registration password")
            raise RuntimeError(f"Error setting the Wazuh agent registration password: {error_output}")

        logger.debug("Wazuh agent registration password set successfully")

    def set_manager_keystore(self, client: paramiko.SSHClient | None = None):
        """
        Sets the manager's indexer credentials in its keystore, retrying on lock contention.

        `wazuh-manager-keystore` needs exclusive access to a RocksDB-backed file that a manager
        daemon started moments earlier may still be opening, since a systemd unit reporting
        "active" doesn't mean every daemon inside it has finished initializing. That race makes
        the CLI fail intermittently right after the manager starts, so each key is retried by exit
        status instead of failing on the first attempt.

        Args:
            client (paramiko.SSHClient | None, optional): An SSH client to execute the commands
                remotely. If None, the commands are executed locally. Defaults to None.

        Raises:
            RuntimeError: If a keystore value could not be set after all retries.
        """

        for key in ("username", "password"):
            command = f"sudo /var/wazuh-manager/bin/wazuh-manager-keystore -f indexer -k {key} -v wazuh-manager"

            for attempt in range(MANAGER_KEYSTORE_MAX_RETRIES):
                _, error_output, returncode = exec_command_with_status(command=command, client=client)
                if returncode == 0:
                    break
                logger.debug(
                    f"Manager keystore {key} not set yet, retrying in {MANAGER_KEYSTORE_WAIT_TIME} seconds "
                    f"(attempt {attempt + 1}/{MANAGER_KEYSTORE_MAX_RETRIES})"
                )
                time.sleep(MANAGER_KEYSTORE_WAIT_TIME)
            else:
                logger.error(f"Error setting manager keystore {key}")
                raise RuntimeError(f"Error setting manager keystore {key}: {error_output}")

    def set_agent_ssl_ca(self, client: paramiko.SSHClient | None = None):
        """
        Provisions the Wazuh agent's trusted CA for the manager's HTTPS transport.

        Copies the manager's self-signed remoted certificate, with the proper ownership and
        permissions, to the path the agent's ``<certificate_authorities>`` configuration points
        to. This lets the pre-installed agent verify the manager's TLS certificate on
        enrollment/connection now that ``verification_mode`` is enforced by default, and
        reproduces the behavior of the ``WAZUH_REGISTRATION_CA`` installation parameter for the
        pre-installed agent shipped in the OVA and AMI.

        Args:
            client (paramiko.SSHClient | None, optional): An SSH client to execute the commands
                remotely. If None, the commands are executed locally. Defaults to None.

        Raises:
            RuntimeError: If the agent trusted CA cannot be set.
        """

        logger.debug("Setting the Wazuh agent trusted CA from the manager remoted certificate")

        command = f"""
            sudo mkdir -p {Path(WAZUH_AGENT_CA_FILE).parent}
            sudo cp {WAZUH_MANAGER_REMOTED_CERT_FILE} {WAZUH_AGENT_CA_FILE}
            sudo chown root:wazuh {WAZUH_AGENT_CA_FILE}
            sudo chmod 640 {WAZUH_AGENT_CA_FILE}
            """
        _, error_output = exec_command(command=command, client=client)
        if error_output:
            logger.error("Error setting the Wazuh agent trusted CA")
            raise RuntimeError(f"Error setting the Wazuh agent trusted CA: {error_output}")

        logger.debug("Wazuh agent trusted CA set successfully")
